-- Magnitude Analysis
-- Compare the measure values by categories
-- It helps us understand the importance of different categories
-- Like total sales by country, Total Quantity by Category etc

SELECT * FROM gold.dim_customers
SELECT * FROM gold.dim_products
SELECT * FROM gold.fact_sales

-- Find total customers by countries
SELECT 
country,
COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_id) DESC

-- Find total customers by gender
SELECT 
gender,
COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_id) DESC

-- Find total products by category
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT(product_key) DESC

-- What is the average costs in each category?
SELECT
category,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC

-- What is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY SUM(f.sales_amount) DESC
-- Usually start with the Fact the LEFT join the dimensions to it
-- Revenue means total sales

-- Find total revenue is generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY SUM(f.sales_amount) DESC

-- What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(f.quantity) total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY SUM(f.quantity) DESC

-- High Cardinality Dimension - Dimension with large number of unique values
-- Low Cardinality Dimension - Dimension with few unique values